#!/bin/bash
#PBS -l walltime=5:00:00,select=1:ncpus=12:mem=64gb
#PBS -A st-singha53-1
#PBS -N fastqc
#PBS -M amrit.singh@ubc.ca
#PBS -o ofastqc.txt
#PBS -e efastqc.txt
  
#############################################################################

module load apptainer

DATA=/project/st-singha53-1/singha53/scrnaseq/data

cd $PBS_O_WORKDIR
apptainer run -B $DATA /project/st-singha53-1/singha53/scrnaseq/scrnaseq.sif make sockeye_fastqc